### ISSUE TITLE
Are there anybody use locally input file to calculate by TESK and how to configuration?

### ISSUE THREAD

**Issue by pengchunhua** [EMBL-EBI-TSI/TESK#125]
Are there anybody use locally input file to calculate by TESK and how to configuration? Anybody can help me?

**Comment by pengchunhua** [comment]
In my deployment I use configuration like this:
        - name: TESK_API_TASKMASTER_ENVIRONMENT_HOST_BASE_PATH
          value: '/nfs'

        - name: TESK_API_TASKMASTER_ENVIRONMENT_CONTAINER_BASE_PATH
          value: '/transfer'

        - name: TESK_API_TASKMASTER_ENVIRONMENT_TRANSFER_PVC_NAME
          value: 'tesk-claim'
but I get the error:
Traceback (most recent call last):
  File "/usr/bin/filer", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/tesk_core/filer.py", line 509, in main
    if process_file(args.transputtype, afile):
  File "/usr/lib/python3.7/site-packages/tesk_core/filer.py", line 464, in process_file
    return transfer.download()
  File "/usr/lib/python3.7/site-packages/tesk_core/filer.py", line 50, in download
    return self.download_file()
  File "/usr/lib/python3.7/site-packages/tesk_core/filer.py", line 173, in download_file
    def download_file(self): self.transfer(shutil.copy  , self.urlContainerPath , self.path)
  File "/usr/lib/python3.7/site-packages/tesk_core/filer.py", line 171, in transfer
    copyFn(src, dst)
  File "/usr/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/transfer/inputs/README.md'
how to solve this problem?

**Comment by aniewielska** [comment]
It would help, if you provided more information.
1) When are you getting the error? (What was the TES API call; specifically which input path led to this error?)
2) How have you configured your PVC (what storage class it is etc)?
3) Is there any README.md file and if so, where?
Answering your question - there were people who successfully used TESK in shared filesystem mode. I assume you read [this](https://github.com/EMBL-EBI-TSI/TESK/blob/master/documentation/deployment_new.md#shared-file-system), as your are trying to set correct variables.

**Comment by pengchunhua** [comment]
than you for your response!
1、I didn't use TES api, I use yaml configuration file to run my job, the job configuration file like this:
{
  "description": "FTP outputting file and directory from volume location",
  "volumes": [
    "/mnt"
  ],
  "inputs": [
    {
      "description": "test local file",
      "path": "/mnt/volumes/file1.txt",
      "type": "FILE",
      "url": "file:///nfs/inputs/README.md"
    }
  ],
  "executors": [
    {
      "image": "10.50.10.48:5000/centos:7",
      "command": [
        "sh",
        "-c",
        "echo 'This goes to file1'"
      ]
    }
  ]
},
I just want to test locally input file, but the error i get.
2、I defined the pvc storage class by myself，it works fine when i use configuration like this:
{
  "description": "FTP outputting file and directory from volume location",
  "volumes": [
    "/mnt"
  ],
  "inputs": [
    {
      "description": "test local file",
      "path": "/mnt/volumes/file1.txt",
      "type": "FILE",
      "content": "file:///nfs/inputs/README.md"
    }
  ],
  "executors": [
    {
      "image": "10.50.10.48:5000/centos:7",
      "command": [
        "sh",
        "-c",
        "echo 'This goes to file1'"
      ]
    }
  ]
}.
3、I try to put the README.md file in path /transfer/inputs and /nfs/inputs/,but it didn't work.Are ther anything I forget?

**Comment by pengchunhua** [comment]
I set my storage class and pvc like this:
# the storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  namespace: nfs-test
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: qgg-nfs-storage 
archiveOnDelete: "false"
reclaimPolicy: Retain
allowVolumeExpansion: true

# the PVC
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tesk-claim
  namespace: tesk-test
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"   #与nfs-StorageClass.yaml metadata.name保持一致
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

**Comment by jtorrex** [comment]
Hi @pengchunhua did you managed to mount the PVC and finally executing the workflow? We are facing some issues similar to you. Mentioning @aniewielska to see if project is still giving some feedback on how to configure the backends.

BR

**Comment by uniqueg** [comment]
Thanks for your interest in the project, @jtorrex. At the moment, we are unsure about the future of TESK. It has been becoming increasingly harder to maintain, and we don't have the resources. An attempt to merge the TESK repos into a single one and replacing the Jave Springboot API with a Python Flask one was left unfinished, which further deteriorated the process. We are currently exploring the [Poiesis](https://poiesis.vercel.app/) (recently developed by @JaeAeich, a long-time contributor to the ELIXIR Cloud & AAI GA4GH Driver Project) as a drop-in replacement, as it comes with a few crucial improvements and is, at least at the moment, actively maintained. If these tests don't cause too much problems for current TESK users, we will likely deprecate TESK.

I am not sure whether Poiesis supports computing on local files at the moment, but maybe you can have a try - or otherwise create an issue in the [Poeisis repo](https://github.com/jaeaeich/poiesis).

Alternatively, or in addition, I recommend you to join the `#tes` channel on the GA4GH Slack board. It's fairly active, so I'm sure someone will be able to help you out. Here's an [invite](https://join.slack.com/t/ga4gh/shared_invite/zt-3ai4o7wfb-qV_0DMLZ9RPpNPZ3~zrMGg) (you will need to manually join the channel).

**Comment by jtorrex** [comment]
Hi!

Thanks for yours answer @uniqueg, we already discovered Poiesis and Funnel, and we're testing them also (in fact, we started to talk with @JaeAeich about one issue with Cromwell https://github.com/JaeAeich/poiesis/issues/71, opened by @NeutryFD
), but as TESK seemed to be the the main backend we tried to work with it.

Thanks also for the invitation to the Slack, we are going to join the `#tes` channel to see if somebody has dealt with a similar configuration (using single PVC for everything), but if not, sure we can seek for some help there.

Regards!
